language: python

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-5.0
    packages:
      - g++-7
      - clang-5.0

sudo: required
dist: xenial

python:
  - "3.5"
  - "3.6"
  - "3.7"

env:
  global:
    - COMPILER=clang++-5.0
    - CXX=clang++-5.0
    - CC=clang-5.0

compiler: clang

branches:
  only:
  - /.*/

install:
  - pip install pipenv codecov
  - pipenv run python setup.py build
  - pipenv run python setup.py bdist_egg
  - pipenv install --dev
script:
  - travis_wait 30 pipenv run pytest --doctest-glob='*.rst' docs/ # Check .rst documentation
  - travis_wait 30 pipenv run pytest -x --doctest-modules --cov=sem/ # Check code and docstrings
  - codecov
