language: python
python:
  - "3.6"
branches:
  only:
  - /.*/
install:
  - pip install pipenv
  - pipenv run python setup.py build
  - pipenv run python setup.py bdist_egg
  - pipenv install --dev
script:
  - pipenv run pytest -x -s
