language: python
python:
  - "3.6"
branches:
  only:
  - /.*/
install:
  - pip install pipenv
  - PIPENV_IGNORE_VIRTUALENVS=1 pipenv run python setup.py build
  - PIPENV_IGNORE_VIRTUALENVS=1 pipenv install --dev
script:
  - PIPENV_IGNORE_VIRTUALENVS=1 pipenv run pytest -x -s
